# 使用官方的 Nginx 镜像
FROM nginx:alpine

# 移除默认的 Nginx 配置
RUN rm -rf /usr/share/nginx/html/*

# 将构建后的React静态文件复制到Nginx容器中
COPY build /usr/share/nginx/html

# 复制自定义的Nginx配置文件
COPY nginx.conf /etc/nginx/conf.d/default.conf

#  docker build -t n7tzu_manufacturer .
#  docker run -d -p 80:80 n7tzu_manufacturer